-- Ajout des valeurs manquantes dans l'enum NewVisitorStatus
-- Correction des erreurs PostgreSQL 22P02 sur /api/v1/souls/stats/kpis

ALTER TYPE "NewVisitorStatus" ADD VALUE IF NOT EXISTS 'FOLLOWING_UP';
ALTER TYPE "NewVisitorStatus" ADD VALUE IF NOT EXISTS 'INACTIVE';
ALTER TYPE "NewVisitorStatus" ADD VALUE IF NOT EXISTS 'ASSIGNED';
ALTER TYPE "NewVisitorStatus" ADD VALUE IF NOT EXISTS 'VISITED';
ALTER TYPE "NewVisitorStatus" ADD VALUE IF NOT EXISTS 'RETURNED_ONCE';
ALTER TYPE "NewVisitorStatus" ADD VALUE IF NOT EXISTS 'RETURNED_TWICE';
ALTER TYPE "NewVisitorStatus" ADD VALUE IF NOT EXISTS 'IN_FD';
ALTER TYPE "NewVisitorStatus" ADD VALUE IF NOT EXISTS 'IN_FOUNDATION';
ALTER TYPE "NewVisitorStatus" ADD VALUE IF NOT EXISTS 'CONSOLIDATED';
ALTER TYPE "NewVisitorStatus" ADD VALUE IF NOT EXISTS 'ACTIVE_MEMBER';
ALTER TYPE "NewVisitorStatus" ADD VALUE IF NOT EXISTS 'SERVING';
ALTER TYPE "NewVisitorStatus" ADD VALUE IF NOT EXISTS 'DISCIPLE_MAKER_TRAINEE';
ALTER TYPE "NewVisitorStatus" ADD VALUE IF NOT EXISTS 'DISCIPLE_MAKER';
ALTER TYPE "NewVisitorStatus" ADD VALUE IF NOT EXISTS 'AT_RISK';
ALTER TYPE "NewVisitorStatus" ADD VALUE IF NOT EXISTS 'TASK_FORCE';
ALTER TYPE "NewVisitorStatus" ADD VALUE IF NOT EXISTS 'LOST';
ALTER TYPE "NewVisitorStatus" ADD VALUE IF NOT EXISTS 'ARCHIVED';